### ISSUE TITLE
fix test test_node_docker.yaml

### ISSUE THREAD

**Issue by ramezsaeed** [Jumpscale/ays_automatic_cockpit_based_testing#57]
jenkins@du-conv-2-jenkins:~/workspace/ays_automatic_cockpit_based_testing$ python3 cockpit_testing/Framework/Driver/Driver.py -b test_node_docker.yaml --teardown
 * Driver is running ..... 
 * Create new account .... 
 * Test case : test_node_docker.yaml
Exception in thread Thread-1:
Traceback (most recent call last):
  File "cockpit_testing/Framework/Driver/Driver.py", line 73, in work
    get_testService_role(blueprint=blueprint, thread_name=threading.current_thread().name)
  File "cockpit_testing/Framework/Driver/Driver.py", line 47, in get_testService_role
    raise NameError("The blueprint doesn't have any test roles.")
NameError: The blueprint doesn't have any test roles.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "cockpit_testing/Framework/Driver/Driver.py", line 105, in work
    error_message = 'ERROR : %s %s' % (traceback.format_exc(), request_cockpit_api.response_error_content)
UnboundLocalError: local variable 'request_cockpit_api' referenced before assignment

**Comment by islamTaha12** [comment]
We didn't write the testing service cause of the following bug:
https://github.com/Jumpscale/ays_jumpscale8/issues/197

So this test case should be skipped till they solve this bug
